### DISCUSSION TITLE
Invididual clamp power in Home Assistant Energy Dashboard

### DISCUSSION THREAD

**Discussion by kbmetz** [JGAguado/Smart_Powermeter#39] [Q&A]
Is there some way to set up the ESPHome config to give each clamp power to the Home Assistant energy dashboard? Right now the only thing I'm able to add is 'daily power' which is nice, but I'd really prefer to be able to add each clamp in as a 'individual device'.

**Comment by JGAguado** [comment]
Dear @kbmetz,

Yes, you can absolutely configure each CT clamp as an individual device on the Home Assistant Energy dashboard using ESPHome — you just need to ensure ESPHome is reporting power in watts (W) with device_class: power and state_class: measurement, and optionally link it to a total_daily_energy sensor to provide energy tracking, something like this for each of the CT clamps you want:

````
sensor:
  - platform: adc
    pin: GPIO1
    id: Input_1
    attenuation: 12db
    update_interval: 1s
    
 - platform: ct_clamp
    sensor: Input_1
    id: probe_1
    name: "Probe 1 Current"
    sample_duration: 200ms
    update_interval: 1s
    filters:
      - calibrate_linear:
          - 0 -> 0
          - 0.042 -> 2.72

  - platform: template
    id: probe_1_power
    name: "Probe 1 Power"
    lambda: |-
      return id(probe_1).state * 230.0;  # Power (W) = Current (A) * Voltage (V)
    unit_of_measurement: 'W'
    device_class: power
    state_class: measurement
    update_interval: 5s

  - platform: total_daily_energy
    id: probe_1_energy
    name: "Probe 1 Energy"
    power_id: probe_1_power
    unit_of_measurement: 'kWh'
    device_class: energy
    state_class: total_increasing

````
