### ISSUE TITLE
Measurements with `SCT-013-000` and the built-in 22R resistor seem close to identical

### ISSUE THREAD

**Issue by roobre** [JGAguado/Smart_Powermeter#16]
Hi there!

Yesterday I finished assembling my smart power meter but I'm struggling to get it to measure reliably. Trying to go through the calibration step, the device does not seem to be able to discern no current (0A) from 2.1A as measured by an external ammeter (which also matches the expected draw for the load I connected).

The YAML I'm using is as follows:
```
sensor:
  - platform: adc
    pin: GPIO1
    id: Input_1
    attenuation: 11db
    update_interval: 1s
# ...
  - platform: ct_clamp
    name: Probe 1
    id: Probe_1
    sensor: Input_1
    sample_duration: 200ms
    update_interval: 1s
    # filters:
    #   - calibrate_linear:
    #       - 0 -> 0
    #       - 0.042 -> 2.72
# ...
```

Notice the filter section is commented out for calibration. Looking at the logs for lines like:

```
[22:55:16][D][sensor:094]: 'Probe 1': Sending state 0.00176 A with 2 decimals of accuracy
```

I collected ~20 of those lines for a 0A and a 2.1A load and crunched some numbers on a spreadsheet. From that, I got that:
- A 0A load reported an average of `0.001685` with an standard deviation of `0.00028`
- A 2.1A load reported an average of `0.001727` with an standard deviation of `0.00026`

What I understand from these numbers is that measurements of 0W (0A) and ~500W (~2A) are within standard deviation from one another, making them hardly distinguishable.

I wonder if this is expected, or if I'm doing something wrong. I'm fine hacking the meter and replacing the 22R resistors with something higher, but I would like to double-check with you to see if what I'm seeing is the expected behavior, or if on the contrary I'm doing something wrong.

[measurements.ods](https://github.com/JGAguado/Smart_Powermeter/files/14037611/measurements.ods)
